version: '3.8'

services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql_cpcm
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:
    driver: local

networks:
  mynetwork:
    driver: bridge